name: cl

networks:
  primary:
    name: primary
  secondary:
    name: secondary

services:
  rabbit-1:
    image: rabbitmq:4-management
    hostname: rabbit-1
    networks:
      - primary
    ports:
      - "8081:15672"
    volumes:
      - ./rabbit.cluster.conf:/config/rabbitmq.conf:z
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq.conf
      - RABBITMQ_ERLANG_COOKIE=${ERLANG_COOKIE}

  rabbit-2:
    image: rabbitmq:4-management
    hostname: rabbit-2
    networks:
      - primary
    ports:
      - "8082:15672"
    volumes:
      - ./rabbit.cluster.conf:/config/rabbitmq.conf:z
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq.conf
      - RABBITMQ_ERLANG_COOKIE=${ERLANG_COOKIE}

  rabbit-3:
    image: rabbitmq:4-management
    hostname: rabbit-3
    networks:
      - primary
    ports:
      - "8083:15672"
    volumes:
      - ./rabbit.cluster.conf:/config/rabbitmq.conf:z
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq.conf
      - RABBITMQ_ERLANG_COOKIE=${ERLANG_COOKIE}

  producer-1:
    profiles: [client]
    image: pivotalrabbitmq/perf-test:latest
    networks: [primary, secondary]
    command: |
      --uri "amqp://guest:guest@rabbit-1:5672" --producers 3 --consumers 0 --queue-pattern 'test-1-%d' --queue-pattern-from 10 --queue-pattern-to 20 --rate 10 --size 100
  consumer-1:
    profiles: [client]
    image: pivotalrabbitmq/perf-test:latest
    networks: [primary, secondary]
    command: |
      --uri "amqp://guest:guest@rabbit-2:5672" --producers 0 --consumers 3 --queue-pattern 'test-1-%d' --queue-pattern-from 10 --queue-pattern-to 20 --rate 1000

  producer-2:
    profiles: [client]
    image: pivotalrabbitmq/perf-test:latest
    networks: [primary, secondary]
    command: |
      --uri "amqp://guest:guest@rabbit-2:5672" --producers 3 --consumers 0 --queue-pattern 'test-2-%d' --queue-pattern-from 10 --queue-pattern-to 20 --rate 10 --size 100
  consumer-2:
    profiles: [client]
    image: pivotalrabbitmq/perf-test:latest
    networks: [primary, secondary]
    command: |
      --uri "amqp://guest:guest@rabbit-3:5672" --producers 0 --consumers 3 --queue-pattern 'test-2-%d' --queue-pattern-from 10 --queue-pattern-to 20 --rate 1000

  producer-3:
    profiles: [client]
    image: pivotalrabbitmq/perf-test:latest
    networks: [primary, secondary]
    command: |
      --uri "amqp://guest:guest@rabbit-3:5672" --producers 3 --consumers 0 --queue-pattern 'test-3-%d' --queue-pattern-from 10 --queue-pattern-to 20 --rate 10 --size 100
  consumer-3:
    profiles: [client]
    image: pivotalrabbitmq/perf-test:latest
    networks: [primary, secondary]
    command: |
      --uri "amqp://guest:guest@rabbit-1:5672" --producers 0 --consumers 3 --queue-pattern 'test-3-%d' --queue-pattern-from 10 --queue-pattern-to 20 --rate 1000

  tools:
    profiles: [tool]
    image: tools
    networks:
      - primary
      - secondary

  perf-test:
    profiles: [tool]
    image: pivotalrabbitmq/perf-test:latest
    networks:
      - primary
      - secondary
    command: >
      --uri "amqp://guest:guest@rabbit-1:5672,amqp://guest:guest@rabbit-2:5672,amqp://guest:guest@rabbit-3:5672"
      --producers 3
      --consumers 3
      --queue-pattern 'test-1-%d'
      --queue-pattern-from 1
      --queue-pattern-to 10
      --rate 1000
      --size 1000
      --autoack
      --metrics-prometheus
      --metrics-prometheus-port 8080
