#!/bin/bash

set -o pipefail

(curl -m 2 -k -u guest:guest localhost:8081/api/nodes 2> /dev/null | jq ".[] | { from: \"rabbit-1\", name, partitions }") && exit 0 || echo "could not reach rabbit-1"
(curl -m 2 -k -u guest:guest localhost:8082/api/nodes 2> /dev/null | jq ".[] | { from: \"rabbit-2\", name, partitions }") && exit 0 || echo "could not reach rabbit-2"
(curl -m 2 -k -u guest:guest localhost:8083/api/nodes 2> /dev/null | jq ".[] | { from: \"rabbit-3\", name, partitions }") && exit 0 || echo "could not reach rabbit-3"
